### ISSUE TITLE
Error using anatpreproc: template not found

### ISSUE THREAD

**Issue by NetRaider89** [zuoxinian/CCS#1]
Lines 108 and 119 of script H1/ccs_01_anatpreproc.sh need the file ${CCSDIR}/templates/MNI152_T1_1mm_first_brain_mask.nii.gz which is not in the repository.

Is it ok to use the template with the same name in the folder ${FSLDIR}/data/standard/MNI152_T1_1mm_first_brain_mask.nii.gz?

**Comment by zuoxinian** [comment]
Yes. It is ok to use the template in ${FSLDIR}.
